# Generated by Django 3.2.6 on 2022-07-31 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FashionJewellery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Image_main', models.ImageField(upload_to='images/FashionJewellery')),
                ('Image_1', models.ImageField(blank=True, upload_to='images/FashionJewellery')),
                ('Image_2', models.ImageField(blank=True, upload_to='images/FashionJewellery')),
                ('Image_3', models.ImageField(blank=True, upload_to='images/FashionJewellery')),
                ('Image_4', models.ImageField(blank=True, upload_to='images/FashionJewellery')),
                ('Image_5', models.ImageField(blank=True, upload_to='images/FashionJewellery')),
                ('Image_6', models.ImageField(blank=True, upload_to='images/FashionJewellery')),
                ('type', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=90)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=12)),
                ('amount', models.IntegerField()),
                ('paymentmethod', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('SKU', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PreciousJewellery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Image_main', models.ImageField(upload_to='images/PreciousJewellery')),
                ('Image_1', models.ImageField(blank=True, upload_to='images/PreciousJewellery')),
                ('Image_2', models.ImageField(blank=True, upload_to='images/PreciousJewellery')),
                ('Image_3', models.ImageField(blank=True, upload_to='images/PreciousJewellery')),
                ('Image_4', models.ImageField(blank=True, upload_to='images/PreciousJewellery')),
                ('Image_5', models.ImageField(blank=True, upload_to='images/PreciousJewellery')),
                ('Image_6', models.ImageField(blank=True, upload_to='images/PreciousJewellery')),
                ('type', models.CharField(max_length=30)),
                ('Metal', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
    ]
